name: CI - Tests Envs - L9

on:
    push:
        paths:
            - '**.php'
    pull_request:
        paths:
            - '**.php'
    schedule:
        - cron: '0 0 * * *'

jobs:

    PHP80_prefer-lowest:
        runs-on: ubuntu-latest

        name: "Tests - PHP: 8.0 - Laravel: V9.0 - prefer-lowest"

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run all job steps
              uses: ./.github/actions/shared
              with:
                  php-version: 8.0
                  composer-stability: prefer-lowest

    PHP80_prefer-stable:
        runs-on: ubuntu-latest

        # needs: [PHP80_prefer-lowest]

        name: "Tests - PHP: 8.0 - Laravel: V9.0 - prefer-stable"

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run all job steps
              uses: ./.github/actions/shared
              with:
                  php-version: 8.0
                  composer-stability: prefer-stable

    PHP81_prefer-lowest:
        runs-on: ubuntu-latest

        # needs: [PHP80_prefer-stable]

        name: "Tests - PHP: 8.1 - Laravel: V9.0 - prefer-lowest"

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run all job steps
              uses: ./.github/actions/shared
              with:
                  php-version: 8.1
                  composer-stability: prefer-lowest

    PHP81_prefer-stable:
        runs-on: ubuntu-latest

        # needs: [PHP81_prefer-lowest]

        name: "Tests - PHP: 8.1 - Laravel: V9.0 - prefer-stable"

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run all job steps
              uses: ./.github/actions/shared
              with:
                  php-version: 8.1
                  composer-stability: prefer-stable
